### PR TITLE
Mcollette/add features

### PR DESCRIPTION
**Pull request by MatthieuCOLLETTE**

### CODE REVIEW

**Comment by MatthieuCOLLETTE** [comment]
Some patches have not been applied.

Two about breaking all parameters / arguments if one is broken. The provided behaviour is NOT to break the first one.

One about hard coding a Devialet style, I prefer providing a .clang-format configuration file instead.

**Comment by faudebert** [comment]
For me, `master` corresponds to `clang` upstream. Maybe we should merge in something else? (ex. `devialet`, ...).

**Comment by MatthieuCOLLETTE** [comment]
Using the latest commit, it is possible to use -style=Devialet option to apply our own style.

.clang-format could still be use if you want to try some settings.

Have fun !

**Comment by dguillois** [comment]
LGTM but i think it is better to follow the clang coding style.

**Review by dguillois — APPROVED** [review]

**Pull request merged**
